<?php

function slider($imagenes,$alto){

?><div class="envoltorio">

	<?php 
	
		$DIR_PLUGIN_SLIDER = URL_PLUGIN."/slider_jquery";
	
		?>
	    <!-- #region Jssor Slider Begin -->
	
	    <!-- Generated by Jssor Slider Maker. -->
	    <!-- This demo works with jquery library -->
	
	    <script type="text/javascript" src="<?php echo $DIR_PLUGIN_SLIDER; ?>/js/jssor.slider.mini.js"></script>
	    <!-- use jssor.slider.debug.js instead for debug -->
	    <script>
	        jQuery(document).ready(function ($) {
	            
	            var jssor_1_SlideoTransitions = [
	              
	            ];
	            
	            var jssor_1_options = {
	              $AutoPlay: true,
	              $SlideDuration: 800,
	              $SlideEasing: $Jease$.$OutQuint,
	              $CaptionSliderOptions: {
	                $Class: $JssorCaptionSlideo$,
	                $Transitions: jssor_1_SlideoTransitions
	              },
	              $ArrowNavigatorOptions: {
	                $Class: $JssorArrowNavigator$
	              },
	              $BulletNavigatorOptions: {
	                $Class: $JssorBulletNavigator$
	              }
	            };
	            
	            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
	            
	            //responsive code begin
	            //you can remove responsive code if you don't want the slider scales while window resizing
	            function ScaleSlider() {
	                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
	                if (refSize) {
	                    refSize = Math.min(refSize, 1180);
	                    jssor_1_slider.$ScaleWidth(refSize);
	                }
	                else {
	                    window.setTimeout(ScaleSlider, 30);
	                }
	            }
	            ScaleSlider();
	            $(window).bind("load", ScaleSlider);
	            $(window).bind("resize", ScaleSlider);
	            $(window).bind("orientationchange", ScaleSlider);
	            //responsive code end
	        });
	    </script>
	
	    <style>
	        
	        /* jssor slider bullet navigator skin 05 css */
	        /*
	        .jssorb05 div           (normal)
	        .jssorb05 div:hover     (normal mouseover)
	        .jssorb05 .av           (active)
	        .jssorb05 .av:hover     (active mouseover)
	        .jssorb05 .dn           (mousedown)
	        */
	        .jssorb05 {
	            position: absolute;
	        }
	        .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
	            position: absolute;
	            /* size of bullet elment */
	            width: 16px;
	            height: 16px;
	            background: url('<?php echo $DIR_PLUGIN_SLIDER; ?>/img/b05.png') no-repeat;
	            overflow: hidden;
	            cursor: pointer;
	        }
	        .jssorb05 div { background-position: -7px -7px; }
	        .jssorb05 div:hover, .jssorb05 .av:hover { background-position: -37px -7px; }
	        .jssorb05 .av { background-position: -67px -7px; }
	        .jssorb05 .dn, .jssorb05 .dn:hover { background-position: -97px -7px; }
	
	        /* jssor slider arrow navigator skin 22 css */
	        /*
	        .jssora22l                  (normal)
	        .jssora22r                  (normal)
	        .jssora22l:hover            (normal mouseover)
	        .jssora22r:hover            (normal mouseover)
	        .jssora22l.jssora22ldn      (mousedown)
	        .jssora22r.jssora22rdn      (mousedown)
	        */
	        .jssora22l, .jssora22r {
	            display: block;
	            position: absolute;
	            /* size of arrow element */
	            width: 40px;
	            height: 58px;
	            cursor: pointer;
	            background: url('<?php echo $DIR_PLUGIN_SLIDER; ?>/img/a22.png') center center no-repeat;
	            overflow: hidden;
	        }
	        .jssora22l { background-position: -10px -31px; }
	        .jssora22r { background-position: -70px -31px; }
	        .jssora22l:hover { background-position: -130px -31px; }
	        .jssora22r:hover { background-position: -190px -31px; }
	        .jssora22l.jssora22ldn { background-position: -250px -31px; }
	        .jssora22r.jssora22rdn { background-position: -310px -31px; }
	    </style>
	
	
	    <div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 1180px; height: <?php echo $alto; ?>px; overflow: hidden; visibility: hidden;">
	        <!-- Loading Screen -->
	        <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
	            <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
	            <div style="position:absolute;display:block;background:url('<?php echo $DIR_PLUGIN_SLIDER; ?>/img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
	        </div>
			
			
	        <div data-u="slides" class='slider_main' style="cursor: default; position: relative; top: 0px; left: 0px; width: 1180px; height: <?php echo $alto; ?>px; overflow: hidden;">
			
				<?php for($i=0;$i<count($imagenes);$i++){ ?>
					<div data-p="225.00" style="display: none;">
						<img data-u="image" src="<?php echo $imagenes[$i]?>" />
					</div>		
				<?php } ?>
				
	           
	        
	        </div>
			
	        <!-- Bullet Navigator -->
	        <div data-u="navigator" class="jssorb05" style="bottom:16px;right:16px;" data-autocenter="1">
	            <!-- bullet navigator item prototype -->
	            <div data-u="prototype" style="width:16px;height:16px;"></div>
	        </div>
			
	        <!-- Arrow Navigator -->
	        <span data-u="arrowleft" class="jssora22l" style="top:0px;left:12px;width:40px;height:58px;" data-autocenter="2"></span>
	        <span data-u="arrowright" class="jssora22r" style="top:0px;right:12px;width:40px;height:58px;" data-autocenter="2"></span>
	    </div>
	
	    <!-- #endregion Jssor Slider End -->
    
    </div>
    
<?php 	
}


function fancybox($ancho=780,$alto=300,$recargar=false){
	?>
	
	<script type="text/javascript" src="<?php echo URL_PLUGIN; ?>/fancybox/source/jquery.fancybox.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="<?php echo URL_PLUGIN; ?>/fancybox/source/jquery.fancybox.css?v=2.1.5" media="screen" />
	<script type="text/javascript">
		$(document).ready(function() {
			/*
			 *  Simple image gallery. Uses default settings
			 */

			$('.fancybox').fancybox({		
				'width'				: <?php echo $ancho; ?>,
				'height'			: <?php echo $alto; ?>,
				'autoScale'			: true,
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',
				'type'				: 'iframe',
				<?php if($recargar){?>
				'afterClose':function () {
					window.location.reload();
				}
				<?php } ?>
			});

			$('.fancybox_link').fancybox({		

				'autoScale'			: true,
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',

			});


			$('.fancybox_normal').fancybox({		
				'width'				: <?php echo $ancho; ?>,
				'height'			: <?php echo $alto; ?>,
				'autoScale'			: true,
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',
				'type'				: 'iframe',
			});

			$('.fancybox_envio').fancybox({		
				'width'				: <?php echo $ancho; ?>,
				'height'			: <?php echo $alto; ?>,
				'autoScale'			: true,
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',
				'type'				: 'iframe',
				'beforeClose'		: function(){ 

						//SCRIPT QUE ACTUALIZA EL SELECT CON LOS CAMBIOS REALIZADOS POR EL VENDEDOR
						$.ajax({
							type: "POST",
							url: "ajax.php",
							data: { PAGINA: 'AJAX', TABLA:'direcciones_envio_select',IDUSUARIO: $("#IDUSUARIO_ENVIO").val(),IDENVIO:$('#etiqueta_envio_select').val()}
						})
						.done(function(msg){

							$('#etiqueta_envio_select').html(msg);

						});	
			
				},
				'closeClick': true
			});
			


			$('.fancybox_factu').fancybox({		
				'width'				: <?php echo $ancho; ?>,
				'height'			: <?php echo $alto; ?>,
				'autoScale'			: true,
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',
				'type'				: 'iframe',
				'beforeClose'		: function(){ 

						//SCRIPT QUE ACTUALIZA EL SELECT CON LOS CAMBIOS REALIZADOS POR EL VENDEDOR
						$.ajax({
							type: "POST",
							url: "ajax.php",
							data: { PAGINA: 'AJAX', TABLA:'direcciones_factu_select',IDUSUARIO: $("#IDUSUARIO_ENVIO").val(),IDENVIO:$('#etiqueta_factu_select').val()}
						})
						.done(function(msg){

							$('#etiqueta_factu_select').html(msg);

						});	
			
				},
				'closeClick': true
			});


		});
	</script>
	<?php
}



function datepicker($config=""){
	?>
<script src="<?php echo URL_PLUGIN; ?>/datepicker/jquery-1.7.1.js"></script>
<link rel="stylesheet" href="<?php echo URL_PLUGIN; ?>/datepicker/jquery.ui.all.css">
<script src="<?php echo URL_PLUGIN; ?>/datepicker/jquery.ui.core.js"></script>
<script src="<?php echo URL_PLUGIN; ?>/datepicker/jquery.ui.datepicker.js"></script>

<script>

	$(function() {
		$( ".datepicker" ).datepicker({
			showButtonPanel: true,
			dateFormat: 'yy-mm-dd', 
			minDate: '0', 
			maxDate: '+15D', 
			changeMonth: true, 
			changeYear: true, 
			numberOfMonths: 1, 
			dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], 
			monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo','Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], 
			monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr','May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
		});

	});
</script>

<script type="text/javascript">
$(function() {
	$('#fecha').datetimepicker({
		defaultDate: "+1w",
		numberOfMonths: 1,
		dateFormat: 'yy-mm-dd',
		timeFormat: 'hh:mm:00'
	});
}
</script>

<script>

	$(function() {
		$( ".fecha_restringida" ).datepicker({
			showButtonPanel: true,
			dateFormat: 'yy-mm-dd', 
			minDate: '+<?php echo $config['ENTREGADESDE']; ?>D', 
			maxDate: '+<?php echo $config['ENTREGAHASTA']; ?>D', 
			changeMonth: true, 
			changeYear: true, 
			numberOfMonths: 1, 
			dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], 
			monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo','Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], 
			monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr','May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
		});

	});
</script>

<script>

	$(function() {
		$( ".fecha_sin_restriccion" ).datepicker({
			showButtonPanel: true,
			dateFormat: 'yy-mm-dd',  
			changeMonth: true, 
			changeYear: true, 
			numberOfMonths: 1, 
			dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], 
			monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo','Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], 
			monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr','May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
		});

	});
</script>

<script>

	$(function() {
		$( ".fecha_escoger" ).datepicker({
			showButtonPanel: true,
			dateFormat: 'yy-mm-dd', 
			minDate: '+1D', 
			maxDate: '+30D', 
			changeMonth: true, 
			changeYear: true, 
			numberOfMonths: 1, 
			dayNamesMin: ['Do', 'Lu', 'Ma', 'Mi', 'Ju', 'Vi', 'Sa'], 
			monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo','Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'], 
			monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr','May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']
		});

	});
</script>
<?php
}

function swf_upload($tipo,$KEYMAIN){

	global $AYV;
	?>
	<!-- swfupload-->	
			<?php $this->etiquetas_html->titulo_editor('Gestionar Stock y colores');	?>
			
			<link href="<?php echo URL_PLUGIN; ?>/swfupload/css/default.css" rel="stylesheet" type="text/css" />
			<script type="text/javascript" src="<?php echo URL_PLUGIN; ?>/swfupload/swfupload/swfupload.js"></script>
			<script type="text/javascript" src="<?php echo URL_PLUGIN; ?>/swfupload/js/swfupload.queue.js"></script>
			<script type="text/javascript" src="<?php echo URL_PLUGIN; ?>/swfupload/js/fileprogress.js"></script>
			<script type="text/javascript" src="<?php echo URL_PLUGIN; ?>/swfupload/js/handlers.js"></script>
			<script type="text/javascript">
					var upload1, upload2;

					window.onload = function() {
						upload1 = new SWFUpload({
							// Backend Settings
							upload_url: "<?php echo URL_PLUGIN; ?>/swfupload/upload.php",
							post_params: {"IDPUBLICACION" : "<?php echo $_GET['IDPRODUCTO']; ?>","TIPO" : "<?php echo $tipo; ?>"},
							
							// File Upload Settings
							file_size_limit : "2048", // 100MB
							file_types : "*.*",
							file_types_description : "All Files",
							file_upload_limit : "100",
							file_queue_limit : "30",

							// Event Handler Settings (all my handlers are in the Handler.js file)
							file_dialog_start_handler : fileDialogStart,
							file_queued_handler : fileQueued,
							file_queue_error_handler : fileQueueError,
							file_dialog_complete_handler : fileDialogComplete,
							upload_start_handler : uploadStart,
							upload_progress_handler : uploadProgress,
							upload_error_handler : uploadError,
							upload_success_handler : uploadSuccess,
							upload_complete_handler : uploadComplete,

							// Button Settings
							button_image_url : "<?php echo URL_PLUGIN; ?>/swfupload/XPButtonUploadText_61x22.png",
							button_placeholder_id : "spanButtonPlaceholder1",
							button_width: 61,
							button_height: 22,
							
							// Flash Settings
							flash_url : "<?php echo URL_PLUGIN; ?>/swfupload/swfupload/swfupload.swf",
							

							custom_settings : {
								progressTarget : "fsUploadProgress1",
								cancelButtonId : "btnCancel1"
							},
							
							// Debug Settings
							debug: false
						});
					 }
				</script>
				
			<!-- swfupload-->
			
			
			<div id="galeriadeimagenes">
				<table>
					<tr valign="top">
						<td>
							<div>
								<div class="fieldset flash" id="fsUploadProgress1">
									<span class="legend">Suba sus imagenes desde aqui</span>
								</div>
								<div style="padding-left: 5px;">
									<span id="spanButtonPlaceholder1"></span>
									<input id="btnCancel1" type="button" value="Cancel Uploads" onclick="cancelQueue(upload1);" disabled="disabled" style="margin-left: 2px; height: 22px; font-size: 8pt;" /><a class='fancybox enlace_boton' href="<?php echo get_option("admin"); ?>/galeria.php?ventana=popup&TIPOPUBLICACION=<?php echo $tipo; ?>&IDPRODUCTO=<?php if($_GET[$KEYMAIN]>0){echo $_GET[$KEYMAIN]; }else{ echo $IDGALERIATEMPORAL; } ?>">&nbsp;Editar Imagenes</a>
									<br />
								</div>
							</div>
						</td>
					</tr>
				</table>
			</div>
	<?php
	}

	
	//test_array($_SERVER);
	function mensaje_error(){
		if($_GET['caso']='error'){
			switch($_GET['display']){
				case'email':
					$mensaje = "Su email es incorrecto o no existe";
				break;
				case'pass':
					$mensaje = "Contrase&ntilde;a incorrecta";
				break;			
				case'void':
					$mensaje = "Debe ingresar su usuario y contrase&ntilde;a";
				break;	
				default:
					$mensaje = "";
				break;
			}
		}
		
		return $mensaje;
	}	
?>